"""initial_cvpro_schema

Revision ID: d554db3efc63
Revises: 
Create Date: 2026-10-03 08:11:05.359805
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd554db3efc63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cvpro_premium_price',
    sa.Column('id', sa.SmallInteger(), server_default='1', autoincrement=False, nullable=False),
    sa.Column('amount_dzd', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='DZD', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency = 'DZD'", name=op.f('ck_cvpro_premium_price_dzd_only')),
    sa.CheckConstraint('amount_dzd >= 0', name=op.f('ck_cvpro_premium_price_nonnegative_amount')),
    sa.CheckConstraint('id = 1', name=op.f('ck_cvpro_premium_price_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cvpro_premium_price'))
    )
    op.create_table('cvpro_templates',
    sa.Column('code', sa.String(length=32), server_default='moderne', nullable=False),
    sa.Column('name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code IN ('moderne', 'classique', 'elegant', 'minimaliste', 'creatif')", name=op.f('ck_cvpro_templates_five_template_codes')),
    sa.CheckConstraint('display_order BETWEEN 0 AND 4', name=op.f('ck_cvpro_templates_valid_display_order')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_cvpro_templates'))
    )
    op.create_table('cvpro_users',
    sa.Column('sub', sa.String(length=255), server_default='', nullable=False),
    sa.Column('email', sa.String(length=320), server_default='', nullable=False),
    sa.Column('name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('role', sa.String(length=16), server_default='member', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'member')", name=op.f('ck_cvpro_users_valid_role')),
    sa.CheckConstraint('length(btrim(sub)) > 0', name=op.f('ck_cvpro_users_sub_not_empty')),
    sa.PrimaryKeyConstraint('sub', name=op.f('pk_cvpro_users'))
    )
    op.create_table('cvpro_admin_bootstrap',
    sa.Column('id', sa.SmallInteger(), server_default='1', autoincrement=False, nullable=False),
    sa.Column('admin_sub', sa.String(length=255), server_default='', nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_cvpro_admin_bootstrap_singleton')),
    sa.CheckConstraint('length(btrim(admin_sub)) > 0', name=op.f('ck_cvpro_admin_bootstrap_admin_sub_not_empty')),
    sa.ForeignKeyConstraint(['admin_sub'], ['cvpro_users.sub'], name=op.f('fk_cvpro_admin_bootstrap_admin_sub_cvpro_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cvpro_admin_bootstrap')),
    sa.UniqueConstraint('admin_sub')
    )
    op.create_table('cvpro_cvs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_sub', sa.String(length=255), server_default='', nullable=False),
    sa.Column('title', sa.String(length=255), server_default='Mon CV', nullable=False),
    sa.Column('template_code', sa.String(length=32), server_default='moderne', nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('information', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(information) = 'object'", name=op.f('ck_cvpro_cvs_information_object')),
    sa.CheckConstraint("jsonb_typeof(sections) = 'array'", name=op.f('ck_cvpro_cvs_sections_array')),
    sa.CheckConstraint('length(btrim(owner_sub)) > 0', name=op.f('ck_cvpro_cvs_owner_not_empty')),
    sa.CheckConstraint('length(btrim(title)) > 0', name=op.f('ck_cvpro_cvs_title_not_empty')),
    sa.CheckConstraint('schema_version >= 1', name=op.f('ck_cvpro_cvs_positive_schema_version')),
    sa.ForeignKeyConstraint(['owner_sub'], ['cvpro_users.sub'], name=op.f('fk_cvpro_cvs_owner_sub_cvpro_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_code'], ['cvpro_templates.code'], name=op.f('fk_cvpro_cvs_template_code_cvpro_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cvpro_cvs')),
    sa.UniqueConstraint('id', 'owner_sub', name='uq_cvpro_cvs_id_owner')
    )
    op.create_index('ix_cvpro_cvs_owner_updated', 'cvpro_cvs', ['owner_sub', 'updated_at'], unique=False)
    op.create_table('cvpro_demo_purchases',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_sub', sa.String(length=255), server_default='', nullable=False),
    sa.Column('cv_id', sa.Uuid(), server_default=sa.text("'00000000-0000-0000-0000-000000000000'::uuid"), nullable=False),
    sa.Column('price_dzd', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='DZD', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency = 'DZD'", name=op.f('ck_cvpro_demo_purchases_dzd_only')),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'cancelled')", name=op.f('ck_cvpro_demo_purchases_valid_status')),
    sa.CheckConstraint('is_demo = true', name=op.f('ck_cvpro_demo_purchases_demo_only')),
    sa.CheckConstraint('length(btrim(owner_sub)) > 0', name=op.f('ck_cvpro_demo_purchases_owner_not_empty')),
    sa.CheckConstraint('price_dzd >= 0', name=op.f('ck_cvpro_demo_purchases_nonnegative_price')),
    sa.ForeignKeyConstraint(['cv_id', 'owner_sub'], ['cvpro_cvs.id', 'cvpro_cvs.owner_sub'], name='fk_cvpro_purchase_owned_cv', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_sub'], ['cvpro_users.sub'], name=op.f('fk_cvpro_demo_purchases_owner_sub_cvpro_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cvpro_demo_purchases'))
    )
    op.create_index('ix_cvpro_demo_purchases_cv_owner', 'cvpro_demo_purchases', ['cv_id', 'owner_sub'], unique=False)
    op.create_index('ix_cvpro_demo_purchases_owner_created', 'cvpro_demo_purchases', ['owner_sub', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cvpro_demo_purchases_owner_created', table_name='cvpro_demo_purchases')
    op.drop_index('ix_cvpro_demo_purchases_cv_owner', table_name='cvpro_demo_purchases')
    op.drop_table('cvpro_demo_purchases')
    op.drop_index('ix_cvpro_cvs_owner_updated', table_name='cvpro_cvs')
    op.drop_table('cvpro_cvs')
    op.drop_table('cvpro_admin_bootstrap')
    op.drop_table('cvpro_users')
    op.drop_table('cvpro_templates')
    op.drop_table('cvpro_premium_price')
    # ### end Alembic commands ###
